random_seed: 42
min_occurrences: 100
clip_length: 12
batch_size: 4
frame_width: 480
frame_height: 270 
num_epochs: 15
val_split: 2
train_ratio: 0.80
learning_rate: 0.001
weight_decay: 0.001
cross_attention_dim: 128
hidden_layer_dim: 512
warmup_epochs: 5
temperature: 2.0
gradient_clipping: 5.0
sgd_momentum: 0.9 
guidance_scale: 1.0
fpn_out_channels: 256
