random_seed: 42
min_occurrences: 100
clip_length: 16
batch_size: 32
frame_width: 480
frame_height: 270 
num_epochs: 16
val_split: 2
train_ratio: 0.80
learning_rate: 0.001
weight_decay: 0.001
attention_module_common_dim: 256
hidden_layer_dim: 512
warmup_epochs: 5
consistency_loss_weight: 0.0
temperature: 1.5
gradient_clipping: 5.0
sgd_momentum: 0.9 
guidance_scale: 1.0
fpn_out_channels: 256